ARG PREBUILD_IMAGE=revaulter-prebuild
FROM ${PREBUILD_IMAGE} AS prebuild

FROM gcr.io/distroless/static-debian12:nonroot
# Default path for the trust store
ENV TRUST_STORE_PATH=/data/trust.json
COPY --from=prebuild /revaulter-cli /bin
ENTRYPOINT ["/bin/revaulter-cli"]
